language: php

git:
  depth: false

sudo: false
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential

# ---------------------------------------------------------------------------------------

_jobs_no_tests: &jobs_no_tests
  script:
    - find . -name '*.php' -not -path "./vendor/*" -not -path "./Tests/*" | xargs -n 1 -P4 php -l

_jobs_full: &jobs_full
  script:
    - make dev -B
    - find . -name '*.php' -not -path "./vendor/*" -not -path "./Tests/*" | xargs -n 1 -P4 php -l
    - make test -B

# ---------------------------------------------------------------------------------------

jobs:
  fast_finish: true
  include:
    - name: "PHP 5.6 - Analyze"
      php: "5.6"
      <<: *jobs_no_tests
    - name: "PHP 7.0 - Analyze"
      php: "7.0"
      <<: *jobs_no_tests
    - name: "PHP 7.1 - Analyze"
      php: "7.1"
      <<: *jobs_no_tests
    - name: "PHP 7.2 - Analyze + Tests"
      php: "7.2"
      <<: *jobs_full
    - name: "PHP 7.3 - Analyze + Tests"
      php: "7.3"
      <<: *jobs_full
    - name: "PHP 7.4 - Analyze + Tests"
      php: "7.4"
      <<: *jobs_full
    - name: "PHP 8.0 - Analyze + Tests"
      php: "8.0.0"
      <<: *jobs_full