name: 'Build Plugin'
description: "Builds the Plugin"

inputs:
  shopware:
    description: "The Shopware version that is used to build the plugin"
    required: true

runs:
  using: "composite"
  steps:

    - name: Start Docker
      shell: bash
      run: |
        docker run --rm --name shop -d dockware/dev:${{ inputs.shopware }}
        sleep 20
        docker logs shop

    - name: Upload into Docker
      shell: bash
      run: |
        docker cp $(pwd)/. shop:/var/www/html/custom/plugins/MollieShopware
        docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'

    # --------------------------------------------------------------------------------------------------------------------------------------

    - name: Build Plugin
      shell: bash
      run: |
        docker exec shop bash -c 'cd /var/www/html/custom/plugins/MollieShopware && make release'

    # --------------------------------------------------------------------------------------------------------------------------------------

    - name: Download ZIP File
      shell: bash
      run: |
        docker cp shop:/var/www/html/custom/plugins/.build/MollieShopware.zip ~/.build/MollieShopware.zip

    - name: Extract ZIP file for artifact
      shell: bash
      run: |
        unzip ~/.build/MollieShopware.zip -d ~/.build/MollieShopware

    - name: Store ZIP file in Github
      uses: actions/upload-artifact@v4
      with:
        name: MollieShopware-Shopware-${{ inputs.shopware }}
        retention-days: 4
        path: ~/.build/MollieShopware

    - name: Delete TMP files
      shell: bash
      run: |
        rm -rf ~/.build/MollieShopware